pipeline{
    agent any
    environment{
        IMAGE_NAME = "manojkrishnappa/mddevopsmasterclass:${GIT_COMMIT}"
    }
    stages{
        stage('Git-Checkout'){
            steps{
                git url: 'https://github.com/ManojKRISHNAPPA/md-devops-masterclass.git', branch: 'main'
            }
        }

        stage('Build'){
            steps{
                sh '''
                    printenv
                    pwd
                    cd code/
                    docker build -t ${IMAGE_NAME} .
                '''
            }
        }

        // stage('testing the image'){
        //     steps{
        //         sh '''
        //             docker kill c1
        //             docker rm c1
        //             docker run -it -d --name c1 -p 9001:8501 ${IMAGE_NAME}
        //         '''
        //     }
        // }

        stage('docker-hub-login'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                }
            }
        }

        stage('Pushing to Registry'){
            steps{
                sh '''
                    docker push ${IMAGE_NAME}
                '''
            }
        }
    }
}