pipeline{
    agent any
    environment{
        IMAGE_NAME = "manojkrishnappa/md-devops-masterclass:${GIT_COMMIT}"
    }
    stages{
        stage('Git-Checkout'){
            steps{
                git url: 'https://github.com/ManojKRISHNAPPA/md-devops-masterclass.git', branch: 'main'
            }
        }

        stage('Build'){
            steps{
                sh '''
                    printenv
                    pwd
                    docker build -t ${IMAGE_NAME} .
                '''
            }
        }
    }
}