pipeline{
    agent any
    environment{
        IMAGE_NAME = "manojkrishnappa/mddevopsmasterclass:${GIT_COMMIT}"
        AWS_REGION = "us-west-2"
        CLUSTER_NAME = "itkannadigaru-cluster"
        NAMESPACE = "microdegree"
    }
    stages{
        stage('Git-Checkout'){
            steps{
                git url: 'https://github.com/ManojKRISHNAPPA/md-devops-masterclass.git', branch: 'main'
            }
        }

        stage('Build'){
            steps{
                sh '''
                    printenv
                    pwd
                    cd code/
                    docker build -t ${IMAGE_NAME} .
                '''
            }
        }

        // stage('testing the image'){
        //     steps{
        //         sh '''
        //             docker kill c1
        //             docker rm c1
        //             docker run -it -d --name c1 -p 9001:8501 ${IMAGE_NAME}
        //         '''
        //     }
        // }

        stage('docker-hub-login'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                }
            }
        }

        stage('Pushing to Registry'){
            steps{
                sh '''
                    docker push ${IMAGE_NAME}
                '''
            }
        }
        stage('Cluster-Update') {
                steps {
                    sh '''
                        aws eks update-kubeconfig \
                        --region ${AWS_REGION} \
                        --name ${CLUSTER_NAME}
                    '''
                }
            }

        stage('Deploying to EKS clsuter') {
                steps {
                    withKubeConfig(
                        caCertificate: '',
                        clusterName: 'itkannadigaru-cluster',
                        contextName: '',
                        credentialsId: 'kube',
                        namespace: 'microdegree',
                        restrictKubeConfigAccess: false,
                        serverUrl: 'https://CF999C939872E1A7F31339FFF97198D3.gr7.us-west-2.eks.amazonaws.com'
                    ) {
                        sh '''
                          pwd
                          cd code
                          pwd
                          sed -i "s|replace|${IMAGE_NAME}|g" deployment.yaml 
                          kubectl apply -f deployment.yaml -n ${NAMESPACE}
                        '''
                    }
                }
            }

            stage('Verify the deployment') {
                steps {
                    withKubeConfig(
                        caCertificate: '',
                        clusterName: 'itkannadigaru-cluster',
                        contextName: '',
                        credentialsId: 'kube',
                        namespace: 'microdegree',
                        restrictKubeConfigAccess: false,
                        serverUrl: 'https://CF999C939872E1A7F31339FFF97198D3.gr7.us-west-2.eks.amazonaws.com'
                    ) {
                        sh "kubectl get pods -n ${NAMESPACE}"
                        sh "kubectl get svc -n ${NAMESPACE}"
                    }
                }
            }        
    }
}